version: '2'
services:
     collectd:
#         image: fr3nd/collectd
         build: collectd
           #INFLUXB: 13.210.153.32
         network_mode: host
         container_name: collectd
         volumes:
             - /proc:/mnt/proc:ro
         privileged: true
     telegraf:
#         image: telegraf
         hostname: leon-ubuntu
         build: telegraf
           #INFLUXB: 13.210.153.32
#         network_mode: host
         container_name: telegraf
         volumes:
             - /var/run/docker.sock:/var/run/docker.sock:ro
             - /sys:/rootfs/sys:ro
             - /proc:/rootfs/proc:ro
             - /etc:/rootfs/etc:ro
         environment:
             - HOST_PROC=/rootfs/proc
             - HOST_SYS=/rootfs/sys
             - HOST_ETC=/rootfs/etc
         extra_hosts:
             - "influxdb:13.210.153.32"
         privileged: true      
         restart: always

