version: '2'
#volumes:
#     influxdb:
#     grafana:
services:
#clients
#     collectd:
#         build: collectd
#         network_mode: host
#         volumes:
#             - /proc:/mnt/proc:ro
#         privileged: true
#         restart: unless-stopped
#clients
     telegraf:
#         image: telegraf
         hostname: $hostname
         build: telegraf
           #INFLUXB: 13.210.153.32
#         network_mode: host
#         container_name: telegraf
         volumes:
             - /var/run/docker.sock:/var/run/docker.sock:ro
             - /sys:/rootfs/sys:ro
             - /proc:/rootfs/proc:ro
             - /etc:/rootfs/etc:ro
         environment:
             - HOST_PROC=/rootfs/proc
             - HOST_SYS=/rootfs/sys
             - HOST_ETC=/rootfs/etc
         extra_hosts:
             - "influxdb:52.64.148.2"
         privileged: true      
         restart: unless-stopped

